### ISSUE TITLE
Vue JSX does not support spread.

### ISSUE THREAD

**Issue by nickmessing** [egoist/codepan#25]
When using spread vue's JSX transform adds an `import` which can not be handled at the moment. You can replicate that by trying:
```js
const App = {
  data: () => ({
  	sel: 2
  }),
  render() {
    return (
      <input type="checkbox" {...{}} />
    );
  }
}

new Vue({
  el: '#app',
  render: h => h(App)
})
```

**Comment by egoist** [comment]
I just added a <kbd>view compiled</kbd> so that you could know what happened behind the scene:

<img width="634" alt="2017-07-20 4 49 48" src="https://user-images.githubusercontent.com/8784712/28408910-8ec78602-6d6b-11e7-834c-7f79c3a3fc27.png">

<img width="892" alt="2017-07-20 4 49 37" src="https://user-images.githubusercontent.com/8784712/28408922-969e8af6-6d6b-11e7-9bf4-5c59c6910095.png">

I guess we can simply:

```js
import merge from '!raw-loader!babel-helper-vue-jsx-merge-props'

transformedCode.replace(/import _mergeJSXProps from "babel-helper-vue-jsx-merge-props";/, merge)
```

**Comment by nickmessing** [comment]
I was thinking of:
```
import('babel-helper-vue-jsx-merge-props').then(vueMergeJSXProps => window.vueMergeJSXProps = vueMergeJSXProps)

/*...*/

transformedCode.replace(/import ([_$a-zA-Z\xA0-\uFFFF][_$a-zA-Z0-9\xA0-\uFFFF]*) from ['"]babel-helper-vue-jsx-merge-props['"];?/, 'const $1 = window.vueMergeJSXProps)
```

I guess `"` and `;` are not likely to disappear but babel's naming is unpredictable with their versions and should be universal.
